machine:
  node:
    version: 6.9.1
  java:
    version: oraclejdk8
  environment:
    PATH: "${PATH}:${HOME}/${CIRCLE_PROJECT_REPONAME}/node_modules/.bin"

branches:
  only:
    - master

dependencies:
  pre:
    - rm -rf ~/.yarn
    - npm install --global yarn
  override:
    - mvn --batch-mode install
  cache_directories:
    - ~/.cache/yarn

test:
  override:
    - echo true

general:
  artifacts:
    - '**/target/*.jar'
    - '**/target/*.war'
    - '**/target/classes/features.xml'

deployment:
  website:
    branch: master
    owner: hawtio
    commands:
      - git config --global user.email "circleci@mail.com"
      - git config --global user.name "CircleCI"
      - ./ci-website.sh

