# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/hawtio
    docker:
      - image: circleci/openjdk:8-browsers
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "pom.xml" }}
      - run:
          command: mvn --batch-mode install
          environment:
            MAVEN_OPTS: -showversion -Xms256m -Xmx4096m
      - save_cache:
          paths:
            - ~/.m2
          key: dependency-cache-{{ checksum "pom.xml" }}
